### ISSUE TITLE
Hello, where is the adapter modules of the iamge_encoder invoked?

### ISSUE THREAD

**Issue by yulin-yf** [cchen-cc/MA-SAM#1]
![0b9a18f3ae06784f5ac6bdd1d4323cf](https://github.com/cchen-cc/MA-SAM/assets/94375166/739ea236-494f-4287-b0af-19a36872ed4b)

**Comment by cchen-cc** [comment]
The adapter modules were inserted into the image encoder in the sam_fact_tt_image_encoder.py script, inside the class _Fact_tt_Block().

![image](https://github.com/cchen-cc/MA-SAM/assets/44825962/d5a591f8-4560-4270-84c5-7719b441629a)
