### ISSUE TITLE
I dont have acess to  BTCV dataset:

### ISSUE THREAD

**Issue by carlotita22** [cchen-cc/MA-SAM#3]
I registered but it says that the data does not exist, could you tell how the dataset is organized? folder distribution.
I imagine that the preprocessing code you uploaded is enough to upload it to training?
Could you tell me the route? It is so I can preprocess my 3D data and test the network

**Comment by cchen-cc** [comment]
Hello, if you click on the challenge website link I provided, you should see a page similar to the one attached below, where you can directly download the raw data. For your other questions, what do you mean by 'route'? I didn't quite understand your question.
![image](https://github.com/cchen-cc/MA-SAM/assets/44825962/2b7fd7e8-b12d-432b-bb36-f3e468898b66)

**Comment by carlotita22** [comment]
Sorry I expressed myself wrong, I am referring to the steps to be able to use my own data.
For example, how the raw data for the preprocessing script is ordered.

**Comment by cchen-cc** [comment]
You can refer to the examples of preprocessing scripts here (https://github.com/cchen-cc/MA-SAM/tree/main/preprocessing).

**Comment by carlotita22** [comment]
thanks you!
