### ISSUE TITLE
about surgical data

### ISSUE THREAD

**Issue by zaneoo** [cchen-cc/MA-SAM#4]
nice work, thanks~
would you mind release your dataset preparation and preprocess codes for surgical data (I mean the EndoVis dataset)? thanks so much.

**Comment by cchen-cc** [comment]
Hello, you can find the preprocessing code for Endovis18 data here (https://github.com/cchen-cc/MA-SAM/blob/main/preprocessing/util_script_endovis18.py)

**Comment by zaneoo** [comment]
> Hello, you can find the preprocessing code for Endovis18 data here (https://github.com/cchen-cc/MA-SAM/blob/main/preprocessing/util_script_endovis18.py)

appreciate
