### ISSUE TITLE
Preprocessing

### ISSUE THREAD

**Issue by carlotita22** [cchen-cc/MA-SAM#5]
Hello! I have a question, why do you rotate the image in the MRI (prostate) preprocessing? In case I don't rotate my images or "flatten" them or use 5 slices per slice, could the code work? (I am segmenting an area of the heart)
Another question, in the preprocessing a csv appears for validation, but I think there is no validation in the training, right?

Thanks so much for reading,
Greetings

**Comment by cchen-cc** [comment]
I used rotation on CT images to have a better visualization of organs, and the rotation on MRI images is just because I want to have a consistency of preprocessing on different datasets. The rotation is not necessary. 
Yes, there is no validation in the training.
